### ISSUE TITLE
Quick review

### ISSUE THREAD

**Issue by strumswell** [Musa00789/FYP#1]
Hey Musa,
As I already told you, I was unable to get your app running via Expo and therefor could not do an in-depth debugging session. What I could do was the following though:

I created a new Veramo agent node app with your agent setup as a basis. Afterwards, I implemented your VC and VP issuance methods trying to mimic the data your passing in during issuance. After running some tests, I can tell you that your veramo agent setup is correct and your `agent.createVerifiablePresentation` and `agent.createVerifiableCredential` method calls are also correct. This tells me, that something is off in the code you do around it, like e.g.:
- saving or retrieving data from you sqlite db
- general react (native) lifecycle issues
- calling the the veramo method during your on-press somehow does not work

You telling me that `TypeError: [Undefined is not a function]` also does not directly hint at Veramo and does hint at what I mentioned above. Sadly, I can not go deeper than that because I can not get the app running. This might hint at your project setup or me just not being knowledgable enough with React native setups. My knowledge on mobile development is limited to Swift on iOS. :)

Now, while going through you code, I noticed a few things that are a little off from an SSI perspective:
- When you create a new VC, you define a `Credentials` field within `credentialSubject`. This is rather weird because you should be defining explicit key values here and not some super generic field. https://github.com/Musa00789/FYP/blob/5b212c3b6afb8bd3e1bdde04b845e8923dac2435/src/Screens/VCScreens/NewVC.tsx#L154
- When defining values in the `credentialSubject` they should be covered/ defined by a JSON-LD context provided in the `@context` definitions. An easy start is to limit yourself on https://www.w3.org/2018/credentials/examples/v1 or stuff from https://schema.org. This does not blow up because you issue JWT VCs/ VPs instead of JSON-LD ones. 
- When creating a VP, the `@context` should not be given blindly the context from the VC because it contains the context definitions exclusive to the VC. Just leave it empty. Veramo will inject the correct standard context definitions. https://github.com/Musa00789/FYP/blob/5b212c3b6afb8bd3e1bdde04b845e8923dac2435/src/Screens/VPScreens/NewVP.tsx#L132
- When creating a VP, the type should not be given blindly the type from the VC because it contains the types exclusive to the VC. Just leave it empty. Veramo will inject the correct standard type. https://github.com/Musa00789/FYP/blob/5b212c3b6afb8bd3e1bdde04b845e8923dac2435/src/Screens/VPScreens/NewVP.tsx#L133C1-L133C1

Looking at those mistakes, I feel like you haven't completely understood how things work technically and from a standard perspective. SSI is a super complex topic where knowledge of different areas has to be understood and then work together. This includes, firstly, knowledge about the DID, VC, VPs (+ addon specs like DIDComm, WACI, Aries RFCs, OIDC4VC, BBS+, ......) specs and then knowledge around digital signatures, blockchain, ZKP circuits, and many more. This takes a lot of time, especially if you want to build an SSI wallet trying to do everything.

This is also why I can't offer you a meeting or something similar. It's just too much to ask and learn in one session. This will take time. You should either read up or use some SSI provider that takes a lot of the technical burden off of your shoulders and eases some of the learning processes. I would advise you using something like https://trinsic.id/ - I know some people working there and their platform is very easy to use and they have amazing documentation and learning pages. 

EDIT on DIDComm: If you want to enable DIDComm between two (or the same for devs sake) Veramo agents, you need to anchor a service endpoint for the receiving DID. Veramo allows this by calling `didManagerAddService` make sure that the Ethereum address behind the did:ethr is funded with ETH to carry out the on-chain transaction to anchor the DIDComm endpoint to the blockchain. For further, help check Veramos tests because you can see usage their. It's pretty tricky. Also a tip on how to get the Ethereum address of the did: Get the publicKeyHex out of the veramo db and use the method out of `import {toEthereumAddress} from '@veramo/did-provider-ethr/build/ethr-did-provider'`. For encrypted DIDComm, you also need to anchor an encryption key to the sending and receiving DID documents. It should be of type `X25519`. Use `keyManagerCreate` to create one and use `didManagerAddKey` to anchor the key. Make sure the adresses behind the DIDs are funded with ETH. This is a lot of work and might intimidating if you have never done it. 

EDIT on ZKP: You can do this by have a DID with a BBS+ key. Veramo itself has no first-party plugin to do this. But I know Sphereon worked on this and they are using Veramo behind the scenes. Just go through their Github https://github.com/Sphereon-Opensource

**Comment by strumswell** [comment]
Some resources for you to read up on:
- https://www.w3.org/TR/vc-data-model/
- https://www.w3.org/TR/did-core/
- https://identity.foundation/didcomm-messaging/spec/
- https://www.youtube.com/watch?v=J-t6ZKuGBsE

Not to toot too much into my horn, but you can also check the theoretical part of my masters thesis for a quick SSI intro: https://bolte.id/assets/ssi_master_thesis.pdf
(the practical part is pretty out of date by now)

**Comment by Musa00789** [comment]
You have helped me a lot with this valuable overview. I will surely read your masters thesis as you have mentioned. And can you please share your testing code with me, it will help me understand more indepth.
Thank You.

**Comment by strumswell** [comment]
Look around here https://github.com/uport-project/veramo/tree/next/__tests__/shared

I would strongly recommend you looking at Trinsic btw

**Comment by Musa00789** [comment]
Yes, I will take your advice and look into it. 
Thanks.
